oku-ui/pergel

package.json
pnpm-lock.yaml
vitest.config.ts

chore: add vitest

---

.github/workflows/ci.yml
.github/workflows/release.yml
renovate.json

chore: github ci and renovate

---

.github/workflows/autofix.yml
package.json
pnpm-lock.yaml

chore: add npm publish scripts

---

src/commands/os.ts
src/commands/upgrade.ts
src/index.ts
src/os/linux/programs/index.ts
src/utils/index.ts

feat: upgrade commands

---

src/commands/os.ts

There were no information about if program is installed, added.

fix: give information if program is installed

---

os/linux/programs/chrome.sh
os/linux/programs/index.ts
src/commands/os.ts

Google Chrome installation option is added.

feat(ubuntu): google chrome 

---

os/linux/programs/index.ts
os/linux/programs/jq.sh

jq installation option is added

feat(ubuntu):jq installation option is added

---

os/linux/programs/github-desktop.sh
os/linux/programs/index.ts

github desktop installation option is added

feat(ubuntu):github desktop installation option is added

---

src/commands/os.ts

don't check dependencies if program is installed

fix: don't check dependencies if program is installed

---

os/linux/programs/index.ts
os/linux/programs/jq.sh
os/linux/programs/pnpm.sh

feat(pnpm): pnpm installation option is added

---

os/linux/programs/index.ts
os/linux/programs/vscode.sh

vscode installation option is added

feat(ubuntu): vscode installation option is added

---

os/linux/programs/index.ts
os/linux/programs/snap.sh

snap installation option is added

feat(ubuntu): snap installation option is added

---

os/linux/programs/beekeeper-studio.sh
os/linux/programs/index.ts

beekeeper studio installation option is added

feat(ubuntu): beekeeper studio installation option is added

---

os/linux/programs/brew.sh
os/linux/programs/index.ts

brew installation option is added

feat(ubuntu): brew installation option is added

---

os/linux/programs/docker-desktop.sh
os/linux/programs/index.ts

docker desktop installation option is added

feat(ubuntu): docker desktop installation option is added

---

os/linux/programs/bun.sh
os/linux/programs/index.ts
os/linux/programs/unzip.sh

bun and unzip installation is added

feat(ubuntu): bun and unzip installation is added

---

os/linux/programs/unzip.sh

chore: typo update unzip.sh

---

os/linux/programs/beekeeper-studio.sh
os/linux/programs/brew.sh
os/linux/programs/bun.sh
os/linux/programs/chrome.sh
os/linux/programs/curl.sh
os/linux/programs/docker-desktop.sh
os/linux/programs/gdebi.sh
os/linux/programs/git.sh
os/linux/programs/github-desktop.sh
os/linux/programs/index.ts
os/linux/programs/jq.sh
os/linux/programs/nvm.sh
os/linux/programs/pnpm.sh
os/linux/programs/snap.sh
os/linux/programs/unzip.sh
os/linux/programs/vscode.sh
os/linux/programs/wget.sh
src/commands/os.ts

Added uninstall option for programs.

feat(ubuntu): added uninstall option for programs

---

os/linux/programs/index.ts

chore(programs): sorted lists

---

os/linux/programs/beekeeper-studio.sh
os/linux/programs/brew.sh
os/linux/programs/bun.sh
os/linux/programs/chrome.sh
os/linux/programs/curl.sh
os/linux/programs/docker-desktop.sh
os/linux/programs/example.sh
os/linux/programs/gdebi.sh
os/linux/programs/git.sh
os/linux/programs/github-desktop.sh
os/linux/programs/index.ts
os/linux/programs/jq.sh
os/linux/programs/nvm.sh
os/linux/programs/pnpm.sh
os/linux/programs/snap.sh
os/linux/programs/unzip.sh
os/linux/programs/vscode.sh
os/linux/programs/wget.sh
src/commands/os.ts

Fixed unkown operations and dpkg packages.

fix(ubuntu): uninstall

---

os/linux/programs/android-studio.sh
os/linux/programs/index.ts

android-studio installation option is added

feat(ubuntu): android-studio installation option is added

---

os/linux/programs/index.ts
os/linux/programs/starship.sh

starship installation option is added

feat(ubuntu): starship installation option is added

---

.github/workflows/autofix.yml
.github/workflows/ci.yml
.github/workflows/release.yml
package.json
pnpm-lock.yaml

chore: upgrade dependencies

---

packages/cli/playground/package.json
packages/cli/src/commands/install.ts
pnpm-lock.yaml

Pergel install was not working in the subfolder inside the Examples folder.

fix(cli): improving install ability in children folder

---

packages/nuxt/src/runtime/core/setupModules.ts

core: fix options bug fixed

---

themes/pergel-ionic/assets/themes/dark.css
themes/pergel-ionic/components/AtomIcon.vue
themes/pergel-ionic/composables/useSettings.ts
themes/pergel-ionic/pages/settings/appearance.vue
themes/pergel-ionic/types/index.ts

fix(ionic): dark mode

---

packages-core/cli/package.json
packages-core/cli/playground/.config/pergel.ts
packages-core/cli/playground/pergel.config.ts
packages-core/cli/src/commands/init.ts
packages-core/cli/src/utils/writeFilePergel.ts

- `.config/` directory support following [config dir proposal](https://github.com/pi0/config-dir)
`pergel init` it now moves the settings file to the .config file and reads it.

feat(cli): config folder
